name: Exakat

on:
  push:
  # Only run when manually triggered.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  exakat:
    runs-on: ubuntu-latest
    name: "Exakat scan"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Exakat
        uses: docker://exakat/exakat-ga
