name: MarkDown

on:
  # Run on all pushes and on all pull requests.
  push:
  pull_request:
  # Also run this workflow every Monday at 6:00.
  schedule:
    - cron: '0 6 * * 1'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    name: 'Lint Markdown'
    runs-on: ubuntu-latest

    # Don't run the cronjob in this workflow on forks.
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository_owner == 'Yoast')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # This action also handles the caching of the dependencies.
      # https://github.com/actions/setup-node
      - name: Set up node and enable caching of dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # @link https://github.com/DavidAnson/markdownlint-cli2
      # @link https://github.com/DavidAnson/markdownlint
      - name: Install Markdownlint CLI2
        run: npm install -g markdownlint-cli2

      # @link https://github.com/marketplace/actions/problem-matcher-for-markdownlint-cli
      - name: Enable showing issue in PRs
        uses: xt0rted/markdownlint-problem-matcher@v1

      - name: Check markdown with CLI2
        run: markdownlint-cli2
