name: Test

on:
  # Run on all pushes and on all pull requests.
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  #### TEST STAGE ####
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
        phpunit: ['auto']
        coverage: [true]
        experimental: [false]

        include:
          # Test against a version on the low-end of the PHPUnit versions supported for each PHP version.
          # On PHP 5.4 and 5.5, only PHPUnit 4.x is supported and the lowest and the
          # highest supported version would be the same.
          # Using the Composer `--prefer-lowest` option is, unfortunately, not viable, as
          # PHPUnit 4.8.36 doesn't have proper PHP restrictions, which means that it
          # would always be installed as "low", which would break the builds for PHP 7.2+.
          - php: '5.6'
            phpunit: '5.7.21'
            coverage: true
            experimental: false
          - php: '7.0'
            phpunit: '5.7.27'
            coverage: true
            experimental: false
          - php: '7.1'
            phpunit: '5.7.21'
            coverage: true
            experimental: false
          - php: '7.2'
            phpunit: '6.3.1'
            coverage: true
            experimental: false
          - php: '7.3'
            phpunit: '7.2.7'
            coverage: true
            experimental: false
          - php: '7.4'
            phpunit: '8.1.6'
            coverage: true
            experimental: false
          - php: '7.4'
            # Specifically set at 9.6.10 to test functioning on 9.x before the 9.6.11 assertObject*() backports came in.
            phpunit: '9.6.10'
            coverage: true
            experimental: false
          - php: '8.0'
            phpunit: '8.5.16'
            # PHPUnit 8.x does not support code coverage on PHP 8.x.
            coverage: false
            experimental: false
          - php: '8.0'
            phpunit: '9.3.0'
            coverage: true
            experimental: false
          - php: '8.1'
            phpunit: '9.3.0'
            coverage: true
            experimental: false
          - php: '8.2'
            phpunit: '9.3.0'
            coverage: true
            experimental: false
          - php: '8.3'
            phpunit: '9.3.0'
            coverage: true
            experimental: false

          # Experimental builds.
          - php: '8.4'
            phpunit: 'auto' # PHPUnit 9.x.
            coverage: false
            experimental: true

    name: "Tests: PHP ${{ matrix.php }} - PHPUnit: ${{matrix.phpunit}}"

    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: ${{ matrix.coverage == true && 'xdebug' || 'none' }}

      - name: 'Composer: set PHPUnit version for tests'
        if: ${{ matrix.phpunit != 'auto' }}
        run: composer require --no-update phpunit/phpunit:"${{ matrix.phpunit }}" --no-interaction

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-php-dependencies-with-composer
      - name: Install Composer dependencies - normal
        if: matrix.php < '8.3'
        uses: "ramsey/composer-install@v2"
        with:
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Install Composer dependencies - ignore PHP restrictions
        if: matrix.php >= '8.3'
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: --ignore-platform-req=php+
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Run the unit tests
        if: ${{ matrix.coverage == false }}
        run: composer test

      - name: Run the unit tests with code coverage
        if: ${{ matrix.coverage == true }}
        run: composer coverage

      - name: Upload coverage results to Coveralls
        if: ${{ success() && matrix.coverage == true }}
        uses: coverallsapp/github-action@v2
        with:
          file: build/logs/clover.xml
          format: clover
          flag-name: php-${{ matrix.php }}-phpunit-${{ matrix.phpunit }}
          parallel: true

  coveralls-finish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
