name: Test

on:
  # Run on all pushes and on all pull requests.
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  #### TEST STAGE ####
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
        phpunit: ['auto']
        coverage: [true]
        experimental: [false]

        # Mind: code coverage can not be run on PHPUnit 11.2.0 - 11.3.2.
        #
        # Since PHPUnit 10.0, PHPUnit native deprecations would affect the exit code.
        # This has been handled via various work-arounds to avoid the PHPUnit
        # deprecation notices, up to the point where it couldn't be handled anymore *.
        #
        # PHPUnit 11.3.3 changes the default behaviour. PHPUnit deprecation notices will
        # now no longer affect the exit code.
        #
        # * PHPUnit 11.2.0 deprecated the use of `#[CoversClass]` for tests covering traits
        #   in favour of a new `#[CoversTrait]` attributes.
        #   No work-around was available to avoid this deprecation notice other than to
        #   not run code coverage.
        #   @link https://github.com/sebastianbergmann/phpunit/issues/5937

        include:
          # Test against a version on the low-end of the PHPUnit versions supported for each PHP version.
          # Using the Composer `--prefer-lowest` option is, unfortunately, not viable, as
          # it would result PHP 7.1 - 7.4 all using PHPUnit 6.4.4, which is not the intention.
          # It also would run into trouble with PHP 8.5.12 being used on PHP 8.0+, while the
          # 8.5.12 release still contained a bug which makes it incompatible with PHP 8.1+,
          # even though it officially allows for it.
          #
          # Note: PHPUnit 10 is not supported for the PHPUnit Polyfills 3.x branch, so there are
          # no builds against PHPUnit 10!
          - php: '7.1'
            phpunit: '~6.4.4'
            coverage: true
            experimental: false
          - php: '7.2'
            # - PHPUnit 7.0 seems to have an issue with something related to TestListeners, so using PHPUnit 7.1 instead for "low".
            phpunit: '~7.1.0'
            coverage: true
            experimental: false
          - php: '7.3'
            phpunit: '7.2.7'
            coverage: true
            experimental: false
          - php: '7.4'
            phpunit: '8.1.6'
            coverage: true
            experimental: false
          - php: '7.4'
            # Specifically set at 9.6.10 to test functioning on 9.x before the 9.6.11 assertObject*() backports came in.
            phpunit: '9.6.10'
            coverage: true
            experimental: false
          - php: '8.0'
            phpunit: '8.5.16'
            # PHPUnit 8.x does not support code coverage on PHP 8.x.
            coverage: false
            experimental: false
          - php: '8.0'
            phpunit: '9.3.0'
            coverage: true
            experimental: false
          - php: '8.1'
            phpunit: '9.3.0'
            coverage: true
            experimental: false
          - php: '8.2'
            phpunit: '9.3.0'
            coverage: true
            experimental: false
          - php: '8.2'
            phpunit: '~11.1.0' # See note above about PHPUnit 11.2.
            coverage: true
            experimental: false
          - php: '8.3'
            phpunit: '11.0.0'
            coverage: true
            experimental: false
          - php: '8.4'
            phpunit: '11.3.6'
            coverage: true
            experimental: false

          # Experimental builds.
          - php: 'nightly'
            phpunit: '^9.6'
            coverage: false
            experimental: true
          - php: 'nightly'
            phpunit: 'auto' # PHPUnit 11.x.
            coverage: false
            experimental: true

          - php: 'latest'
            phpunit: 'dev-main' # PHPUnit 12.x.
            coverage: false
            experimental: true

    name: "Tests: PHP ${{ matrix.php }} - PHPUnit: ${{matrix.phpunit}}"

    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: ${{ matrix.coverage == true && 'xdebug' || 'none' }}

      # YoastCS 3.0 has a PHP 7.2 minimum which conflicts with the requirements of this package.
      - name: 'Composer: remove YoastCS'
        run: composer remove --dev yoast/yoastcs --no-update --no-interaction

      - name: 'Composer: set PHPUnit version for tests'
        if: ${{ matrix.phpunit != 'auto' }}
        run: composer require --no-update phpunit/phpunit:"${{ matrix.phpunit }}" --no-interaction

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-php-dependencies-with-composer
      - name: Install Composer dependencies - normal
        if: matrix.php != 'nightly'
        uses: "ramsey/composer-install@v3"
        with:
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Install Composer dependencies - ignore PHP restrictions
        if: matrix.php == 'nightly'
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: --ignore-platform-req=php+
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Grab PHPUnit version
        id: phpunit_version
        run: echo "VERSION=$(vendor/bin/phpunit --version | grep --only-matching --max-count=1 --extended-regexp '\b[0-9]+\.[0-9]+')" >> "$GITHUB_OUTPUT"

      - name: "DEBUG: Show grabbed version"
        run: echo ${{ steps.phpunit_version.outputs.VERSION }}

      - name: Determine PHPUnit config
        id: phpunit_config
        run: |
          if [ "${{ matrix.phpunit == 'dev-main' }}" == "true" ]; then
            echo 'FILE=phpunit10.xml.dist' >> "$GITHUB_OUTPUT"
          elif [ "${{ startsWith( steps.phpunit_version.outputs.VERSION, '11.' ) }}" == "true" ]; then
            echo 'FILE=phpunit10.xml.dist' >> "$GITHUB_OUTPUT"
          else
            echo 'FILE=phpunit.xml.dist' >> "$GITHUB_OUTPUT"
          fi

      - name: "Run the unit tests"
        # Don't fail the build on a test run failure against a future PHPUnit version.
        continue-on-error: ${{ matrix.phpunit == 'dev-main' }}
        run: >
          vendor/bin/phpunit -c ${{ steps.phpunit_config.outputs.FILE }}
          ${{ ! matrix.coverage && '--no-coverage' || '' }}

      - name: Upload coverage results to Coveralls
        if: ${{ success() && matrix.coverage == true }}
        uses: coverallsapp/github-action@v2
        with:
          file: build/logs/clover.xml
          format: clover
          flag-name: php-${{ matrix.php }}-phpunit-${{ matrix.phpunit }}
          parallel: true

  test-phar:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # Test against the high/low supported PHP-PHPUnit combinations.
          #
          # Code coverage is only run against the high/high PHP-PHPUnit combinations
          # and very select other combinations.
          # This should be sufficient to record the coverage for the PHAR specific code.

          # PHPUnit 6 is only supported for PHPUnit 6.4.4-latest on the officially supported PHP versions.
          - php: '7.1'
            phpunit: '6.4'
          - php: '7.1'
            phpunit: '6'
          - php: '7.2'
            phpunit: '6.4'
          - php: '7.2'
            phpunit: '6'
            coverage: true

          # PHPUnit 7 is fully supported for the officially supported PHP versions.
          # Caveats:
          # - PHPUnit 7.0 seems to have an issue with something related to TestListeners, so using PHPUnit 7.1 instead for "low".
          # - PHPUnit 7 supports PHP 7.3 as of PHPUnit 7.3.0 (for our purposes).
          - php: '7.1'
            phpunit: '7.1'
          - php: '7.1'
            phpunit: '7'
          - php: '7.3'
            phpunit: '7.3'
          - php: '7.3'
            phpunit: '7'
            coverage: true

          # PHPUnit 8 is fully supported for the officially supported PHP versions.
          # Caveats:
          # - PHPUnit 8 supports PHP 8.0 as of PHPUnit 8.5.12 (for our purposes).
          # - PHPUnit 8 supports PHP 8.1 as of PHPUnit 8.5.19 (for our purposes).
          # - PHPUnit 8 supports PHP 8.2 as of PHPUnit 8.5.19 (for our purposes).
          # - PHPUnit 8 supports PHP 8.3 as of PHPUnit 8.5.19 (for our purposes).
          # - PHPUnit 8 supports PHP 8.4 as of PHPUnit 8.5.40 (for our purposes).
          # - PHPUnit 8 does not support running code coverage on PHP 8.0 or higher.
          - php: '7.2'
            phpunit: '8.0'
            coverage: true
          - php: '7.2'
            phpunit: '8'
          - php: '7.4'
            phpunit: '8'
            coverage: true
          - php: '8.0'
            phpunit: '8.5.12'
          - php: '8.4'
            phpunit: '8.5.40'
          - php: '8.4'
            phpunit: '8'

          # PHPUnit 9 is fully supported for the officially supported PHP versions.
          # Caveats:
          # - PHPUnit 9 supports PHP 8.0 as of PHPUnit 9.3.0 (for our purposes).
          # - PHPUnit 9 supports PHP 8.1 as of PHPUnit 9.5.8 (for our purposes).
          # - PHPUnit 9 supports PHP 8.2 as of PHPUnit 9.5.8 (for our purposes).
          # - PHPUnit 9 supports PHP 8.3 as of PHPUnit 9.5.8 (for our purposes).
          # - PHPUnit 9 supports PHP 8.4 as of PHPUnit 9.6.21 (for our purposes).
          - php: '7.3'
            phpunit: '9.0'
            coverage: true
          - php: '7.3'
            phpunit: '9'
          - php: '8.0'
            phpunit: '9.3.0'
          - php: '8.0'
            phpunit: '9'
          - php: '8.3'
            phpunit: '9.5.8'
          - php: '8.3'
            phpunit: '9'
          - php: '8.4'
            phpunit: '9.6.21'
          - php: '8.4'
            phpunit: '9'
            coverage: true

          # PHPUnit 10 is NOT supported in PHPUnit Polyfills 3.x.

          # PHPUnit 11 is fully supported for the officially supported PHP versions.
          # Caveats:
          # - PHPUnit 11 supports PHP 8.4 as of PHPUnit 11.3.6 (for our purposes).
          #
          # Mind: code coverage can not be run on PHPUnit 11.2.0 - 11.3.2.
          # For a full explanation, see above (in the strategy for the other test job).
          - php: '8.2'
            phpunit: '11.0'
            coverage: true
          - php: '8.2'
            phpunit: '11'
          - php: '8.3'
            phpunit: '11.0'
          - php: '8.3'
            phpunit: '11'
            coverage: true
          - php: '8.4'
            phpunit: '11.3.6'
          - php: '8.4'
            phpunit: '11'
            coverage: true

          # Experimental builds.
          - php: 'nightly'
            phpunit: '9'
          - php: 'nightly'
            phpunit: '11'

    name: "PHAR test: PHP ${{ matrix.php }} - PHPUnit: ${{matrix.phpunit}}"

    continue-on-error: ${{ matrix.php == 'nightly' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          tools: phpunit:${{ matrix.phpunit }}
          coverage: ${{ matrix.coverage && 'xdebug' || 'none' }}
        env:
          fail-fast: true

      # YoastCS 3.0 has a PHP 7.2 minimum which conflicts with the requirements of this package.
      - name: 'Composer: remove YoastCS'
        run: composer remove --dev yoast/yoastcs --no-update --no-interaction

      # Remove PHPUnit from the Composer install as we want to be sure the PHAR file is used.
      - name: 'Composer: remove PHPUnit'
        run: composer remove phpunit/phpunit --no-update --no-interaction

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-php-dependencies-with-composer
      - name: Install Composer dependencies - normal
        if: matrix.php != 'nightly'
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--no-dev"
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Install Composer dependencies - ignore PHP restrictions
        if: matrix.php == 'nightly'
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--no-dev --ignore-platform-req=php+"
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Grab PHPUnit version
        id: phpunit_version
        run: echo "VERSION=$(phpunit --version | grep --only-matching --max-count=1 --extended-regexp '\b[0-9]+\.[0-9]+')" >> "$GITHUB_OUTPUT"

      - name: "DEBUG: Show grabbed version"
        run: echo ${{ steps.phpunit_version.outputs.VERSION }}

      - name: Determine PHPUnit config
        id: phpunit_config
        run: |
          if [ "${{ startsWith( steps.phpunit_version.outputs.VERSION, '11.' ) }}" == "true" ]; then
            echo 'FILE=phpunit10.xml.dist' >> "$GITHUB_OUTPUT"
          else
            echo 'FILE=phpunit.xml.dist' >> "$GITHUB_OUTPUT"
          fi

      - name: "Run the unit tests"
        run: >
          phpunit -c ${{ steps.phpunit_config.outputs.FILE }}
          ${{ ! matrix.coverage && '--no-coverage' || '' }}

      - name: Upload coverage results to Coveralls
        if: ${{ success() && matrix.coverage }}
        uses: coverallsapp/github-action@v2
        with:
          file: build/logs/clover.xml
          format: clover
          flag-name: php-${{ matrix.php }}-phpunit-phar-${{ matrix.phpunit }}
          parallel: true

  coveralls-finish:
    needs: [test, test-phar]
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
